<a href="https://colab.research.google.com/github/krishshah8000/Email-Classification-spam-and-priority-/blob/main/Email_Classification_spam_and_priority.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/completeSpamAssassin.csv')
df

      Unnamed: 0                                               Body  Label
0              0  \nSave up to 70% on Life Insurance.\nWhy Spend...      1
1              1  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
2              2  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
3              3  ##############################################...      1
4              4  I thought you might like these:\n1) Slim Down ...      1
...          ...                                                ...    ...
6041        6041                                              empty      0
6042        6042                    ___           ___           ...      0
6043        6043  IN THIS ISSUE:01. Readers write\n02. Extension...      0
6044        6044                                              empty      0
6045        6045                                              empty      0

[6046 rows x 3 columns]

In [ ]:
if 'Unnamed: 0' in df.columns:
    df = df.drop('Unnamed: 0', axis=1)
df.head()

                                                Body  Label
0  \nSave up to 70% on Life Insurance.\nWhy Spend...      1
1  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
2  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
3  ##############################################...      1
4  I thought you might like these:\n1) Slim Down ...      1

In [ ]:
df_excel = pd.read_excel('/content/spam.xlsx')
df_excel

,"ham Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
0,ham Ok lar... Joking wif u oni...,ham,Ok lar... Joking wif u oni...
1,spam Free entry in 2 a wkly comp to win FA ...,spam,Free entry in 2 a wkly comp to win FA Cup f...
2,ham U dun say so early hor... U c already ...,ham,U dun say so early hor... U c already then...
3,"ham Nah I don't think he goes to usf, he l...",ham,"Nah I don't think he goes to usf, he lives..."
4,spam FreeMsg Hey there darling it's been 3 ...,spam,FreeMsg Hey there darling it's been 3 week'...
...,...,...,...
5568,spam This is the 2nd time we have tried 2 c...,spam,This is the 2nd time we have tried 2 contac...
5569,ham Will ü b going to esplanade fr home?,ham,Will ü b going to esplanade fr home?
5570,"ham Pity, * was in mood for that. So...any...",ham,"Pity, * was in mood for that. So...any oth..."
5571,ham The guy did some bitching but I acted ...,ham,The guy did some bitching but I acted like...
5572,ham Rofl. Its true to its name,ham,Rofl. Its true to its name

In [ ]:
df_excel = df_excel.drop(df_excel.columns[0], axis=1)
df_excel.head()

,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
0,ham,Ok lar... Joking wif u oni...
1,spam,Free entry in 2 a wkly comp to win FA Cup f...
2,ham,U dun say so early hor... U c already then...
3,ham,"Nah I don't think he goes to usf, he lives..."
4,spam,FreeMsg Hey there darling it's been 3 week'...

In [ ]:
df_excel.rename(columns={'ham': 'Label'}, inplace=True)
df_excel.head()

,Label,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
0,ham,Ok lar... Joking wif u oni...
1,spam,Free entry in 2 a wkly comp to win FA Cup f...
2,ham,U dun say so early hor... U c already then...
3,ham,"Nah I don't think he goes to usf, he lives..."
4,spam,FreeMsg Hey there darling it's been 3 week'...

In [ ]:
df_excel['Label'] = df_excel['Label'].replace({'ham': 0, 'spam': 1}).infer_objects(copy=False)
print('Updated unique values in df_excel[\'Label\']:', df_excel['Label'].unique())

Updated unique values in df_excel['Label']: [0 1]

/tmp/ipykernel_8440/3286925434.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_excel['Label'] = df_excel['Label'].replace({'ham': 0, 'spam': 1}).infer_objects(copy=False)

In [ ]:
df_excel.rename(columns={df_excel.columns[1]: 'Body'}, inplace=True)
df_excel.head()

   Label                                               Body
0      0                      Ok lar... Joking wif u oni...
1      1     Free entry in 2 a wkly comp to win FA Cup f...
2      0      U dun say so early hor... U c already then...
3      0      Nah I don't think he goes to usf, he lives...
4      1     FreeMsg Hey there darling it's been 3 week'...

In [ ]:
combined_df = pd.concat([df, df_excel], ignore_index=True)
print(combined_df.head())
print(combined_df.shape)

                                                Body  Label
0  \nSave up to 70% on Life Insurance.\nWhy Spend...      1
1  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
2  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
3  ##############################################...      1
4  I thought you might like these:\n1) Slim Down ...      1
(11619, 2)

In [ ]:
df_spam_or_not_spam = pd.read_csv('/content/spam_or_not_spam.csv')
print(df_spam_or_not_spam.head())
print(df_spam_or_not_spam.shape)

                                               email  label
0   date wed NUMBER aug NUMBER NUMBER NUMBER NUMB...    0.0
1  martin a posted tassos papadopoulos the greek ...    0.0
2  man threatens explosion in moscow thursday aug...    0.0
3  klez the virus that won t die already the most...    0.0
4   in adding cream to spaghetti carbonara which ...    0.0
(3032, 2)

In [ ]:
df_spam_or_not_spam.rename(columns={'email': 'Body', 'label': 'Label'}, inplace=True)
print(df_spam_or_not_spam.head())

                                                Body  Label
0   date wed NUMBER aug NUMBER NUMBER NUMBER NUMB...    0.0
1  martin a posted tassos papadopoulos the greek ...    0.0
2  man threatens explosion in moscow thursday aug...    0.0
3  klez the virus that won t die already the most...    0.0
4   in adding cream to spaghetti carbonara which ...    0.0

In [ ]:
df_spam_or_not_spam.dropna(subset=['Label'], inplace=True)
df_spam_or_not_spam['Label'] = df_spam_or_not_spam['Label'].astype(int)
print(df_spam_or_not_spam.dtypes)

Body     object
Label     int64
dtype: object

In [ ]:
combined_df = pd.concat([combined_df, df_spam_or_not_spam], ignore_index=True)
print(combined_df.head())
print(combined_df.shape)

                                                Body  Label
0  \nSave up to 70% on Life Insurance.\nWhy Spend...      1
1  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
2  1) Fight The Risk of Cancer!\nhttp://www.adcli...      1
3  ##############################################...      1
4  I thought you might like these:\n1) Slim Down ...      1
(14619, 2)

In [ ]:
import re

def remove_urls(text):
    # Ensure the input is a string before applying regex
    if isinstance(text, str):
        url_pattern = re.compile(r'https?://\S+|www\.\S+')
        return url_pattern.sub(r'', text)
    return text  # Return non-string values as they are, or handle them specifically

# Convert 'Body' column to string type to handle any non-string entries (like NaNs) gracefully
combined_df['Body'] = combined_df['Body'].astype(str).apply(remove_urls)

print(combined_df.head())
print(combined_df.shape)

                                                Body  Label
0  \nSave up to 70% on Life Insurance.\nWhy Spend...      1
1  1) Fight The Risk of Cancer!\n Slim Down - Gua...      1
2  1) Fight The Risk of Cancer!\n Slim Down - Gua...      1
3  ##############################################...      1
4  I thought you might like these:\n1) Slim Down ...      1
(14619, 2)

In [ ]:
initial_rows = combined_df.shape[0]
combined_df = combined_df.drop_duplicates()
final_rows = combined_df.shape[0]
duplicates_removed = initial_rows - final_rows

print(f"Initial number of rows: {initial_rows}")
print(f"Final number of rows after removing duplicates: {final_rows}")
print(f"Number of duplicate rows removed: {duplicates_removed}")
print(combined_df.shape)

Initial number of rows: 14619
Final number of rows after removing duplicates: 13298
Number of duplicate rows removed: 1321
(13298, 2)

In [ ]:
import re

def remove_special_characters_and_normalize_spaces(text):
    # Remove all characters that are not alphanumeric or a literal space character
    text = re.sub(r'[^a-zA-Z0-9 ]', '', text)
    # Replace any sequence of one or more whitespace characters with a single space
    text = re.sub(r'\s+', ' ', text)
    # Remove leading/trailing whitespace
    return text.strip()

combined_df['Body'] = combined_df['Body'].apply(remove_special_characters_and_normalize_spaces)

print(combined_df.head())
print(combined_df.shape)

                                                Body  Label
0  Save up to 70 on Life InsuranceWhy Spend More ...      1
1  1 Fight The Risk of Cancer Slim Down Guarantee...      1
2  1 Fight The Risk of Cancer Slim Down Guarantee...      1
3  Adult Club Offers FREE Membership INSTANT ACCE...      1
4  I thought you might like these1 Slim Down Guar...      1
(13298, 2)

In [ ]:
combined_df['word_count'] = combined_df['Body'].apply(lambda x: len(x.split()))
initial_rows = combined_df.shape[0]
combined_df = combined_df[combined_df['word_count'] >= 10]
final_rows = combined_df.shape[0]
removed_rows = initial_rows - final_rows
print(f"Initial number of rows: {initial_rows}")
print(f"Final number of rows after removing short emails: {final_rows}")
print(f"Number of emails with less than 10 words removed: {removed_rows}")
combined_df = combined_df.drop(columns=['word_count'])
print(combined_df.head())
print(combined_df.shape)

Initial number of rows: 13298
Final number of rows after removing short emails: 11119
Number of emails with less than 10 words removed: 2179
                                                Body  Label
0  Save up to 70 on Life InsuranceWhy Spend More ...      1
1  1 Fight The Risk of Cancer Slim Down Guarantee...      1
2  1 Fight The Risk of Cancer Slim Down Guarantee...      1
3  Adult Club Offers FREE Membership INSTANT ACCE...      1
4  I thought you might like these1 Slim Down Guar...      1
(11119, 2)

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Download necessary NLTK data (if not already downloaded)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('punkt', quiet=True)

True

In [ ]:
# 1. Convert all emails to lowercase
combined_df['Body'] = combined_df['Body'].str.lower()
print("Emails converted to lowercase. Sample:")
print(combined_df['Body'].head())

Emails converted to lowercase. Sample:
0    save up to 70 on life insurancewhy spend more ...
1    1 fight the risk of cancer slim down guarantee...
2    1 fight the risk of cancer slim down guarantee...
3    adult club offers free membership instant acce...
4    i thought you might like these1 slim down guar...
Name: Body, dtype: object

In [ ]:
# 2. Remove stopwords
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    return ' '.join([word for word in str(text).split() if word not in stop_words])

combined_df['Body'] = combined_df['Body'].apply(remove_stopwords)
print("Stopwords removed. Sample:")
print(combined_df['Body'].head())

Stopwords removed. Sample:
0    save 70 life insurancewhy spend tolife quote s...
1    1 fight risk cancer slim guaranteed lose 1012 ...
2    1 fight risk cancer slim guaranteed lose 1012 ...
3    adult club offers free membership instant acce...
4    thought might like these1 slim guaranteed lose...
Name: Body, dtype: object

In [ ]:
# 3. Apply Lemmatization
lemmatizer = WordNetLemmatizer()

def apply_lemmatization(text):
    return ' '.join([lemmatizer.lemmatize(word) for word in str(text).split()])

combined_df['Body'] = combined_df['Body'].apply(apply_lemmatization)
print("Lemmatization applied. Sample:")
print(combined_df['Body'].head())

Lemmatization applied. Sample:
0    save 70 life insurancewhy spend tolife quote s...
1    1 fight risk cancer slim guaranteed lose 1012 ...
2    1 fight risk cancer slim guaranteed lose 1012 ...
3    adult club offer free membership instant acces...
4    thought might like these1 slim guaranteed lose...
Name: Body, dtype: object

In [ ]:
# 4. Apply TF-IDF
tfidf_vectorizer = TfidfVectorizer(max_features=5000) # You can adjust max_features
X_tfidf = tfidf_vectorizer.fit_transform(combined_df['Body'])

print("TF-IDF matrix created. Shape:", X_tfidf.shape)
print("Sample of TF-IDF feature names (first 10):", tfidf_vectorizer.get_feature_names_out()[:10])

TF-IDF matrix created. Shape: (11119, 5000)
Sample of TF-IDF feature names (first 10): ['00' '000' '0000' '000000' '001' '0025' '01' '0100' '02' '0200']

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Calculate cosine similarity matrix
cosine_sim_matrix = cosine_similarity(X_tfidf)

# Get the indices of the rows to keep
rows_to_keep = []
duplicate_indices = set()

for i in range(cosine_sim_matrix.shape[0]):
    if i not in duplicate_indices:
        rows_to_keep.append(i)
        for j in range(i + 1, cosine_sim_matrix.shape[0]):
            if cosine_sim_matrix[i, j] > 0.8:
                duplicate_indices.add(j)

# Filter the combined_df to get the unique emails
initial_rows = combined_df.shape[0]
cleaned_df_cosine = combined_df.iloc[rows_to_keep].reset_index(drop=True)
final_rows = cleaned_df_cosine.shape[0]
duplicates_removed_cosine = initial_rows - final_rows

print(f"Initial number of rows: {initial_rows}")
print(f"Final number of rows after removing cosine-similar duplicates: {final_rows}")
print(f"Number of emails removed due to >80% cosine similarity: {duplicates_removed_cosine}")
print("Cleaned dataset head:")
print(cleaned_df_cosine.head())
print("Cleaned dataset shape:", cleaned_df_cosine.shape)

Initial number of rows: 11119
Final number of rows after removing cosine-similar duplicates: 8468
Number of emails removed due to >80% cosine similarity: 2651
Cleaned dataset head:
                                                Body  Label
0  save 70 life insurancewhy spend tolife quote s...      1
1  1 fight risk cancer slim guaranteed lose 1012 ...      1
2  adult club offer free membership instant acces...      1
3  thought might like these1 slim guaranteed lose...      1
4  powerhouse gifting program dont want miss get ...      1
Cleaned dataset shape: (8468, 2)

In [ ]:
from sklearn.model_selection import train_test_split

# Transform the 'Body' column of cleaned_df_cosine using the already fitted tfidf_vectorizer
X = tfidf_vectorizer.transform(cleaned_df_cosine['Body'])

# Assign the 'Label' column to the variable y
y = cleaned_df_cosine['Label']

# Split X and y into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of X_train: (6774, 5000)
Shape of X_test: (1694, 5000)
Shape of y_train: (6774,)
Shape of y_test: (1694,)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

results = {}

In [ ]:
print("--- Re-training Logistic Regression with class_weight='balanced' ---")
# Instantiate a LogisticRegression with random_state=42, solver='liblinear', and class_weight='balanced'
logistic_regression_balanced_model = LogisticRegression(random_state=42, solver='liblinear', class_weight='balanced')

# Fit the Logistic Regression model to the training data
logistic_regression_balanced_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_lr_balanced = logistic_regression_balanced_model.predict(X_test)

# Calculate and print the accuracy score
accuracy_lr_balanced = accuracy_score(y_test, y_pred_lr_balanced)
print(f"Logistic Regression (balanced) Accuracy: {accuracy_lr_balanced:.4f}")

# Generate and print the classification report
report_lr_balanced = classification_report(y_test, y_pred_lr_balanced)
print("Logistic Regression (balanced) Classification Report:")
print(report_lr_balanced)

# Update the results dictionary
results['Logistic Regression (Balanced)'] = {
    'accuracy': accuracy_lr_balanced,
    'report': report_lr_balanced
}

--- Re-training Logistic Regression with class_weight='balanced' ---
Logistic Regression (balanced) Accuracy: 0.9640
Logistic Regression (balanced) Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.97      0.98      1403
           1       0.88      0.91      0.90       291

    accuracy                           0.96      1694
   macro avg       0.93      0.94      0.94      1694
weighted avg       0.96      0.96      0.96      1694

In [ ]:
print("All Model Results:")
for model_name, metrics in results.items():
    print(f"\n--- {model_name} ---")
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print("Classification Report:")
    print(metrics['report'])

All Model Results:

--- Logistic Regression (Balanced) ---
Accuracy: 0.9640
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.97      0.98      1403
           1       0.88      0.91      0.90       291

    accuracy                           0.96      1694
   macro avg       0.93      0.94      0.94      1694
weighted avg       0.96      0.96      0.96      1694

In [ ]:
from sklearn.naive_bayes import MultinomialNB

print("--- Training Logistic Regression (Standard) ---")
# Instantiate a LogisticRegression with random_state=42 and solver='liblinear'
logistic_regression_model = LogisticRegression(random_state=42, solver='liblinear')

# Fit the Logistic Regression model to the training data
logistic_regression_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_lr_standard = logistic_regression_model.predict(X_test)

# Calculate and print the accuracy score
accuracy_lr_standard = accuracy_score(y_test, y_pred_lr_standard)
print(f"Logistic Regression (Standard) Accuracy: {accuracy_lr_standard:.4f}")

# Generate and print the classification report
report_lr_standard = classification_report(y_test, y_pred_lr_standard)
print("Logistic Regression (Standard) Classification Report:")
print(report_lr_standard)

# Update the results dictionary
results['Logistic Regression (Standard)'] = {
    'accuracy': accuracy_lr_standard,
    'report': report_lr_standard
}

--- Training Logistic Regression (Standard) ---
Logistic Regression (Standard) Accuracy: 0.9545
Logistic Regression (Standard) Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97      1403
           1       0.98      0.75      0.85       291

    accuracy                           0.95      1694
   macro avg       0.96      0.87      0.91      1694
weighted avg       0.96      0.95      0.95      1694

In [ ]:
print("\n--- Training Multinomial Naive Bayes ---")
# Instantiate a Multinomial Naive Bayes model
naive_bayes_model = MultinomialNB()

# Fit the Naive Bayes model to the training data
naive_bayes_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_nb = naive_bayes_model.predict(X_test)

# Calculate and print the accuracy score
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print(f"Multinomial Naive Bayes Accuracy: {accuracy_nb:.4f}")

# Generate and print the classification report
report_nb = classification_report(y_test, y_pred_nb)
print("Multinomial Naive Bayes Classification Report:")
print(report_nb)

# Update the results dictionary
results['Multinomial Naive Bayes'] = {
    'accuracy': accuracy_nb,
    'report': report_nb
}

--- Training Multinomial Naive Bayes ---
Multinomial Naive Bayes Accuracy: 0.9540
Multinomial Naive Bayes Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      1403
           1       0.94      0.78      0.85       291

    accuracy                           0.95      1694
   macro avg       0.95      0.89      0.91      1694
weighted avg       0.95      0.95      0.95      1694

In [ ]:
print("\nAll Model Results (updated):")
for model_name, metrics in results.items():
    print(f"\n--- {model_name} ---")
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print("Classification Report:")
    print(metrics['report'])

All Model Results (updated):

--- Logistic Regression (Balanced) ---
Accuracy: 0.9640
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.97      0.98      1403
           1       0.88      0.91      0.90       291

    accuracy                           0.96      1694
   macro avg       0.93      0.94      0.94      1694
weighted avg       0.96      0.96      0.96      1694


--- Logistic Regression (Standard) ---
Accuracy: 0.9545
Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97      1403
           1       0.98      0.75      0.85       291

    accuracy                           0.95      1694
   macro avg       0.96      0.87      0.91      1694
weighted avg       0.96      0.95      0.95      1694


--- Multinomial Naive Bayes ---
Accuracy: 0.9540
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      1403
           1       0.94      0.78      0.85       291

    accuracy                           0.95      1694
   macro avg       0.95      0.89      0.91      1694
weighted avg       0.95      0.95      0.95      1694

In [ ]:
from sklearn.tree import DecisionTreeClassifier

print("\n--- Training Decision Tree Classifier (Balanced) ---")
# Instantiate a DecisionTreeClassifier with random_state=42 and class_weight='balanced'
decision_tree_model = DecisionTreeClassifier(random_state=42, class_weight='balanced')

# Fit the Decision Tree model to the training data
decision_tree_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_dt = decision_tree_model.predict(X_test)

# Calculate and print the accuracy score
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print(f"Decision Tree Accuracy (Balanced): {accuracy_dt:.4f}")

# Generate and print the classification report
report_dt = classification_report(y_test, y_pred_dt)
print("Decision Tree Classification Report (Balanced):")
print(report_dt)

# Update the results dictionary
results['Decision Tree (Balanced)'] = {
    'accuracy': accuracy_dt,
    'report': report_dt
}

--- Training Decision Tree Classifier (Balanced) ---
Decision Tree Accuracy (Balanced): 0.8908
Decision Tree Classification Report (Balanced):
              precision    recall  f1-score   support

           0       0.96      0.91      0.93      1403
           1       0.64      0.82      0.72       291

    accuracy                           0.89      1694
   macro avg       0.80      0.86      0.83      1694
weighted avg       0.91      0.89      0.90      1694

In [ ]:
from sklearn.ensemble import RandomForestClassifier

print("\n--- Training Random Forest Classifier (Balanced) ---")
# Instantiate a RandomForestClassifier with random_state=42 and class_weight='balanced'
random_forest_model_balanced = RandomForestClassifier(random_state=42, class_weight='balanced')

# Fit the Random Forest model to the training data
random_forest_model_balanced.fit(X_train, y_train)

# Make predictions on the test set
y_pred_rf_balanced = random_forest_model_balanced.predict(X_test)

# Calculate and print the accuracy score
accuracy_rf_balanced = accuracy_score(y_test, y_pred_rf_balanced)
print(f"Random Forest Accuracy (Balanced): {accuracy_rf_balanced:.4f}")

# Generate and print the classification report
report_rf_balanced = classification_report(y_test, y_pred_rf_balanced)
print("Random Forest Classification Report (Balanced):")
print(report_rf_balanced)

# Update the results dictionary
results['Random Forest (Balanced)'] = {
    'accuracy': accuracy_rf_balanced,
    'report': report_rf_balanced
}

--- Training Random Forest Classifier (Balanced) ---
Random Forest Accuracy (Balanced): 0.9540
Random Forest Classification Report (Balanced):
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      1403
           1       0.93      0.79      0.86       291

    accuracy                           0.95      1694
   macro avg       0.94      0.89      0.91      1694
weighted avg       0.95      0.95      0.95      1694

In [ ]:
import xgboost as xgb
import numpy as np

print("\n--- Training XGBoost Classifier (Balanced) ---")

# Calculate the scale_pos_weight for handling class imbalance
# This is ratio of negative class count to the positive class count
neg_count = np.sum(y_train == 0)
pos_count = np.sum(y_train == 1)
scale_pos_weight_value = neg_count / pos_count

# Instantiate an XGBClassifier with random_state=42 and scale_pos_weight
xgboost_model_balanced = xgb.XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    use_label_encoder=False,
    random_state=42,
    scale_pos_weight=scale_pos_weight_value
)

# Fit the XGBoost model to the training data
xgboost_model_balanced.fit(X_train, y_train)

# Make predictions on the test set
y_pred_xgb_balanced = xgboost_model_balanced.predict(X_test)

# Calculate and print the accuracy score
accuracy_xgb_balanced = accuracy_score(y_test, y_pred_xgb_balanced)
print(f"XGBoost Accuracy (Balanced): {accuracy_xgb_balanced:.4f}")

# Generate and print the classification report
report_xgb_balanced = classification_report(y_test, y_pred_xgb_balanced)
print("XGBoost Classification Report (Balanced):")
print(report_xgb_balanced)

# Update the results dictionary
results['XGBoost (Balanced)'] = {
    'accuracy': accuracy_xgb_balanced,
    'report': report_xgb_balanced
}

--- Training XGBoost Classifier (Balanced) ---

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [14:00:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBoost Accuracy (Balanced): 0.9604
XGBoost Classification Report (Balanced):
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1403
           1       0.89      0.88      0.88       291

    accuracy                           0.96      1694
   macro avg       0.93      0.93      0.93      1694
weighted avg       0.96      0.96      0.96      1694

In [ ]:
print("\nAll Model Results (updated):")
for model_name, metrics in results.items():
    print(f"\n--- {model_name} ---")
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print("Classification Report:")
    print(metrics['report'])

All Model Results (updated):

--- Logistic Regression (Balanced) ---
Accuracy: 0.9640
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.97      0.98      1403
           1       0.88      0.91      0.90       291

    accuracy                           0.96      1694
   macro avg       0.93      0.94      0.94      1694
weighted avg       0.96      0.96      0.96      1694


--- Logistic Regression (Standard) ---
Accuracy: 0.9545
Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97      1403
           1       0.98      0.75      0.85       291

    accuracy                           0.95      1694
   macro avg       0.96      0.87      0.91      1694
weighted avg       0.96      0.95      0.95      1694


--- Multinomial Naive Bayes ---
Accuracy: 0.9540
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      1403
           1       0.94      0.78      0.85       291

    accuracy                           0.95      1694
   macro avg       0.95      0.89      0.91      1694
weighted avg       0.95      0.95      0.95      1694


--- Decision Tree (Balanced) ---
Accuracy: 0.8908
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.91      0.93      1403
           1       0.64      0.82      0.72       291

    accuracy                           0.89      1694
   macro avg       0.80      0.86      0.83      1694
weighted avg       0.91      0.89      0.90      1694


--- Random Forest (Balanced) ---
Accuracy: 0.9540
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      1403
           1       0.93      0.79      0.86       291

    accuracy                           0.95      1694
   macro avg       0.94      0.89      0.91      1694
weighted avg       0.95      0.95      0.95      1694


--- XGBoost (Balanced) ---
Accuracy: 0.9604
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1403
           1       0.89      0.88      0.88       291

    accuracy                           0.96      1694
   macro avg       0.93      0.93      0.93      1694
weighted avg       0.96      0.96      0.96      1694

In [ ]:
df_emails = pd.read_csv('/content/emails.csv')
print(df_emails.head())
print(df_emails.shape)

                             subject  \
0         URGENT: API Portal is down
1  Urgent: Immediate Action Required
2        Monthly Performance Summary
3           Project Milestone Update
4         Discussion on New Proposal

                                                body priority
0  The API Portal in HR has crashed. We are losin...     High
1  A critical error has been detected in the syst...     High
2  This is for your information and necessary act...   Medium
3  Kindly go through the attached document and re...   Medium
4  This is an update regarding the ongoing projec...   Medium
(7000, 3)

In [ ]:
df_emails = df_emails.drop('subject', axis=1)
print(df_emails.head())
print(df_emails.shape)

                                                body priority
0  The API Portal in HR has crashed. We are losin...     High
1  A critical error has been detected in the syst...     High
2  This is for your information and necessary act...   Medium
3  Kindly go through the attached document and re...   Medium
4  This is an update regarding the ongoing projec...   Medium
(7000, 2)

In [ ]:
df_emails.rename(columns={'body': 'Body'}, inplace=True)
print(df_emails.head())
print(df_emails.shape)

                                                Body priority
0  The API Portal in HR has crashed. We are losin...     High
1  A critical error has been detected in the syst...     High
2  This is for your information and necessary act...   Medium
3  Kindly go through the attached document and re...   Medium
4  This is an update regarding the ongoing projec...   Medium
(7000, 2)

In [ ]:
df_emails['Body'] = df_emails['Body'].astype(str).apply(remove_urls)
df_emails['Body'] = df_emails['Body'].apply(remove_special_characters_and_normalize_spaces)
df_emails['Body'] = df_emails['Body'].str.lower()
df_emails['Body'] = df_emails['Body'].apply(remove_stopwords)
df_emails['Body'] = df_emails['Body'].apply(apply_lemmatization)

print("Preprocessed df_emails head:")
print(df_emails.head())

Preprocessed df_emails head:
                                                Body priority
0  api portal hr crashed losing data immediate fi...     High
1  critical error detected system need fixed imme...     High
2                       information necessary action   Medium
3       kindly go attached document respond possible   Medium
4  update regarding ongoing project let u know qu...   Medium

In [ ]:
X_emails = tfidf_vectorizer.transform(df_emails['Body'])

print("Shape of X_emails (TF-IDF features for df_emails):", X_emails.shape)

Shape of X_emails (TF-IDF features for df_emails): (7000, 5000)

In [ ]:
df_emails['Predicted_Label'] = logistic_regression_balanced_model.predict(X_emails)

print("df_emails with predicted labels:")
print(df_emails.head())

df_emails with predicted labels:
                                                Body priority  Predicted_Label
0  api portal hr crashed losing data immediate fi...     High                0
1  critical error detected system need fixed imme...     High                0
2                       information necessary action   Medium                0
3       kindly go attached document respond possible   Medium                0
4  update regarding ongoing project let u know qu...   Medium                0

In [ ]:
initial_count = df_emails.shape[0]

df_emails = df_emails[df_emails['Predicted_Label'] == 0]

removed_spam_count = initial_count - df_emails.shape[0]

print("df_emails after removing spam (predicted label 1):")
print(df_emails.head())
print(f"Shape of df_emails after removing spam: {df_emails.shape}")
print(f"Total number of emails removed as spam: {removed_spam_count}")

df_emails after removing spam (predicted label 1):
                                                Body priority  Predicted_Label
0  api portal hr crashed losing data immediate fi...     High                0
1  critical error detected system need fixed imme...     High                0
2                       information necessary action   Medium                0
3       kindly go attached document respond possible   Medium                0
4  update regarding ongoing project let u know qu...   Medium                0
Shape of df_emails after removing spam: (6382, 3)
Total number of emails removed as spam: 618

In [ ]:
df_emails = df_emails.drop('Predicted_Label', axis=1)

print("df_emails after removing 'Predicted_Label' column:")

print(f"Shape of df_emails after removing 'Predicted_Label': {df_emails.shape}")

df_emails after removing 'Predicted_Label' column:
Shape of df_emails after removing 'Predicted_Label': (6382, 2)

In [ ]:
df_emails

                                                   Body priority
0     api portal hr crashed losing data immediate fi...     High
1     critical error detected system need fixed imme...     High
2                          information necessary action   Medium
3          kindly go attached document respond possible   Medium
4     update regarding ongoing project let u know qu...   Medium
...                                                 ...      ...
6995  dear sirmadam multiple user reported issue sin...     High
6996  hello pending day kindly treat important ref i...   Medium
6997  good morning situation seems escalating awaiti...     High
6998  hello observed unexpected behavior affecting o...      Low
6999  good morning pending day appreciate support re...   Medium

[6382 rows x 2 columns]

In [ ]:
priority_mapping = {'Low': 0, 'Medium': 1, 'High': 2}
df_emails['priority'] = df_emails['priority'].map(priority_mapping)

print("df_emails head with encoded priority:")
print(df_emails.head())
print("Priority value counts:")
print(df_emails['priority'].value_counts())

df_emails head with encoded priority:
                                                Body  priority
0  api portal hr crashed losing data immediate fi...         2
1  critical error detected system need fixed imme...         2
2                       information necessary action         1
3       kindly go attached document respond possible         1
4  update regarding ongoing project let u know qu...         1
Priority value counts:
priority
2    2664
1    2131
0    1587
Name: count, dtype: int64

In [ ]:
X_priority = tfidf_vectorizer.transform(df_emails['Body'])
y_priority = df_emails['priority']

print(f"Shape of X_priority: {X_priority.shape}")
print(f"Shape of y_priority: {y_priority.shape}")

Shape of X_priority: (6382, 5000)
Shape of y_priority: (6382,)

In [ ]:
from sklearn.model_selection import train_test_split

# Split X_priority and y_priority into training and testing sets
X_train_priority, X_test_priority, y_train_priority, y_test_priority = train_test_split(
    X_priority, y_priority, test_size=0.2, random_state=42, stratify=y_priority
)

# Print the shapes of the newly created training and testing sets
print(f"Shape of X_train_priority: {X_train_priority.shape}")
print(f"Shape of X_test_priority: {X_test_priority.shape}")
print(f"Shape of y_train_priority: {y_train_priority.shape}")
print(f"Shape of y_test_priority: {y_test_priority.shape}")

Shape of X_train_priority: (5105, 5000)
Shape of X_test_priority: (1277, 5000)
Shape of y_train_priority: (5105,)
Shape of y_test_priority: (1277,)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

priority_results = {}
# 1. Instantiate a LogisticRegression model with random_state=42, solver='liblinear', and class_weight='balanced'
logistic_regression_priority_model = LogisticRegression(random_state=42, solver='liblinear', class_weight='balanced')

# 2. Fit the Logistic Regression model to the training data
print("\n--- Training Logistic Regression Model (Balanced) for Priority ---")
logistic_regression_priority_model.fit(X_train_priority, y_train_priority)

# 3. Make predictions on the test set
y_pred_lr_priority = logistic_regression_priority_model.predict(X_test_priority)

# 4. Calculate and print the accuracy score
accuracy_lr_priority = accuracy_score(y_test_priority, y_pred_lr_priority)
print(f"Logistic Regression Priority Accuracy (Balanced): {accuracy_lr_priority:.4f}")

# 5. Generate and print the classification report
report_lr_priority = classification_report(y_test_priority, y_pred_lr_priority)
print("Logistic Regression Priority Classification Report (Balanced):")
print(report_lr_priority)

# Store results for summary
priority_results['Logistic Regression (Balanced)'] = {
    'accuracy': accuracy_lr_priority,
    'report': report_lr_priority
}

--- Training Logistic Regression Model (Balanced) for Priority ---
Logistic Regression Priority Accuracy (Balanced): 0.8865
Logistic Regression Priority Classification Report (Balanced):
              precision    recall  f1-score   support

           0       1.00      0.81      0.90       318
           1       0.95      0.84      0.89       426
           2       0.80      0.97      0.88       533

    accuracy                           0.89      1277
   macro avg       0.92      0.87      0.89      1277
weighted avg       0.90      0.89      0.89      1277

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

print("--- Training Logistic Regression (Standard) for Priority ---")
# Instantiate a LogisticRegression model with random_state=42 and solver='liblinear'
logistic_regression_priority_model_standard = LogisticRegression(random_state=42, solver='liblinear')

# Fit the Logistic Regression model to the training data
logistic_regression_priority_model_standard.fit(X_train_priority, y_train_priority)

# Make predictions on the test set
y_pred_lr_priority_standard = logistic_regression_priority_model_standard.predict(X_test_priority)

# Calculate and print the accuracy score
accuracy_lr_priority_standard = accuracy_score(y_test_priority, y_pred_lr_priority_standard)
print(f"Logistic Regression Priority Accuracy (Standard): {accuracy_lr_priority_standard:.4f}")

# Generate and print the classification report
report_lr_priority_standard = classification_report(y_test_priority, y_pred_lr_priority_standard)
print("Logistic Regression Priority Classification Report (Standard):")
print(report_lr_priority_standard)

# Store results for summary
priority_results['Logistic Regression (Standard)'] = {
    'accuracy': accuracy_lr_priority_standard,
    'report': report_lr_priority_standard
}

--- Training Logistic Regression (Standard) for Priority ---
Logistic Regression Priority Accuracy (Standard): 0.8872
Logistic Regression Priority Classification Report (Standard):
              precision    recall  f1-score   support

           0       1.00      0.81      0.90       318
           1       0.96      0.83      0.89       426
           2       0.80      0.98      0.88       533

    accuracy                           0.89      1277
   macro avg       0.92      0.87      0.89      1277
weighted avg       0.90      0.89      0.89      1277

In [ ]:
print("\n--- Training Multinomial Naive Bayes for Priority ---")
# Instantiate a Multinomial Naive Bayes model
naive_bayes_priority_model = MultinomialNB()

# Fit the Naive Bayes model to the training data
naive_bayes_priority_model.fit(X_train_priority, y_train_priority)

# Make predictions on the test set
y_pred_nb_priority = naive_bayes_priority_model.predict(X_test_priority)

# Calculate and print the accuracy score
accuracy_nb_priority = accuracy_score(y_test_priority, y_pred_nb_priority)
print(f"Multinomial Naive Bayes Priority Accuracy: {accuracy_nb_priority:.4f}")

# Generate and print the classification report
report_nb_priority = classification_report(y_test_priority, y_pred_nb_priority)
print("Multinomial Naive Bayes Priority Classification Report:")
print(report_nb_priority)

# Store results for summary
priority_results['Multinomial Naive Bayes'] = {
    'accuracy': accuracy_nb_priority,
    'report': report_nb_priority
}

--- Training Multinomial Naive Bayes for Priority ---
Multinomial Naive Bayes Priority Accuracy: 0.8825
Multinomial Naive Bayes Priority Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.81      0.90       318
           1       0.98      0.80      0.88       426
           2       0.79      0.99      0.88       533

    accuracy                           0.88      1277
   macro avg       0.92      0.87      0.88      1277
weighted avg       0.90      0.88      0.88      1277

In [ ]:
print("\nAll Priority Model Results (updated):")
for model_name, metrics in priority_results.items():
    print(f"\n--- {model_name} ---")
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print("Classification Report:")
    print(metrics['report'])

All Priority Model Results (updated):

--- Logistic Regression (Balanced) ---
Accuracy: 0.8865
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.81      0.90       318
           1       0.95      0.84      0.89       426
           2       0.80      0.97      0.88       533

    accuracy                           0.89      1277
   macro avg       0.92      0.87      0.89      1277
weighted avg       0.90      0.89      0.89      1277


--- Logistic Regression (Standard) ---
Accuracy: 0.8872
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.81      0.90       318
           1       0.96      0.83      0.89       426
           2       0.80      0.98      0.88       533

    accuracy                           0.89      1277
   macro avg       0.92      0.87      0.89      1277
weighted avg       0.90      0.89      0.89      1277


--- Multinomial Naive Bayes ---
Accuracy: 0.8825
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.81      0.90       318
           1       0.98      0.80      0.88       426
           2       0.79      0.99      0.88       533

    accuracy                           0.88      1277
   macro avg       0.92      0.87      0.88      1277
weighted avg       0.90      0.88      0.88      1277

In [ ]:
from sklearn.tree import DecisionTreeClassifier

print("\n--- Training Decision Tree Classifier (Balanced) for Priority ---")
# Instantiate a DecisionTreeClassifier with random_state=42 and class_weight='balanced'
decision_tree_priority_model = DecisionTreeClassifier(random_state=42, class_weight='balanced')

# Fit the Decision Tree model to the training data
decision_tree_priority_model.fit(X_train_priority, y_train_priority)

# Make predictions on the test set
y_pred_dt_priority = decision_tree_priority_model.predict(X_test_priority)

# Calculate and print the accuracy score
accuracy_dt_priority = accuracy_score(y_test_priority, y_pred_dt_priority)
print(f"Decision Tree Priority Accuracy (Balanced): {accuracy_dt_priority:.4f}")

# Generate and print the classification report
report_dt_priority = classification_report(y_test_priority, y_pred_dt_priority)
print("Decision Tree Priority Classification Report (Balanced):")
print(report_dt_priority)

# Update the priority_results dictionary
priority_results['Decision Tree (Balanced)'] = {
    'accuracy': accuracy_dt_priority,
    'report': report_dt_priority
}

--- Training Decision Tree Classifier (Balanced) for Priority ---
Decision Tree Priority Accuracy (Balanced): 0.8583
Decision Tree Priority Classification Report (Balanced):
              precision    recall  f1-score   support

           0       0.85      0.86      0.85       318
           1       0.87      0.87      0.87       426
           2       0.86      0.85      0.86       533

    accuracy                           0.86      1277
   macro avg       0.86      0.86      0.86      1277
weighted avg       0.86      0.86      0.86      1277

In [ ]:
from sklearn.ensemble import RandomForestClassifier

print("\n--- Training Random Forest Classifier (Balanced) for Priority ---")
# Instantiate a RandomForestClassifier with random_state=42 and class_weight='balanced'
random_forest_priority_model_balanced = RandomForestClassifier(random_state=42, class_weight='balanced')

# Fit the Random Forest model to the training data
random_forest_priority_model_balanced.fit(X_train_priority, y_train_priority)

# Make predictions on the test set
y_pred_rf_priority_balanced = random_forest_priority_model_balanced.predict(X_test_priority)

# Calculate and print the accuracy score
accuracy_rf_priority_balanced = accuracy_score(y_test_priority, y_pred_rf_priority_balanced)
print(f"Random Forest Priority Accuracy (Balanced): {accuracy_rf_priority_balanced:.4f}")

# Generate and print the classification report
report_rf_priority_balanced = classification_report(y_test_priority, y_pred_rf_priority_balanced)
print("Random Forest Priority Classification Report (Balanced):")
print(report_rf_priority_balanced)

# Update the priority_results dictionary
priority_results['Random Forest (Balanced)'] = {
    'accuracy': accuracy_rf_priority_balanced,
    'report': report_rf_priority_balanced
}

--- Training Random Forest Classifier (Balanced) for Priority ---
Random Forest Priority Accuracy (Balanced): 0.8583
Random Forest Priority Classification Report (Balanced):
              precision    recall  f1-score   support

           0       0.87      0.84      0.86       318
           1       0.86      0.86      0.86       426
           2       0.85      0.86      0.86       533

    accuracy                           0.86      1277
   macro avg       0.86      0.86      0.86      1277
weighted avg       0.86      0.86      0.86      1277

In [ ]:
import xgboost as xgb

print("\n--- Training XGBoost Classifier for Priority ---")

# Instantiate an XGBClassifier for multi-class classification
# For multi-class, objective='multi:softmax' and num_class should be specified.
# class_weight is not directly supported for multi-class in XGBoost like in sklearn,
# so we omit scale_pos_weight which is for binary classification.
xgboost_priority_model = xgb.XGBClassifier(
    objective='multi:softmax',
    num_class=len(y_train_priority.unique()), # Set num_class based on unique labels
    eval_metric='mlogloss',
    use_label_encoder=False,
    random_state=42
)

# Fit the XGBoost model to the training data
xgboost_priority_model.fit(X_train_priority, y_train_priority)

# Make predictions on the test set
y_pred_xgb_priority = xgboost_priority_model.predict(X_test_priority)

# Calculate and print the accuracy score
accuracy_xgb_priority = accuracy_score(y_test_priority, y_pred_xgb_priority)
print(f"XGBoost Priority Accuracy: {accuracy_xgb_priority:.4f}")

# Generate and print the classification report
report_xgb_priority = classification_report(y_test_priority, y_pred_xgb_priority)
print("XGBoost Priority Classification Report:")
print(report_xgb_priority)

# Update the priority_results dictionary
priority_results['XGBoost'] = {
    'accuracy': accuracy_xgb_priority,
    'report': report_xgb_priority
}

--- Training XGBoost Classifier for Priority ---

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [14:01:07] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBoost Priority Accuracy: 0.8684
XGBoost Priority Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.82      0.87       318
           1       0.89      0.85      0.87       426
           2       0.83      0.91      0.87       533

    accuracy                           0.87      1277
   macro avg       0.88      0.86      0.87      1277
weighted avg       0.87      0.87      0.87      1277

In [ ]:
print("\nAll Priority Model Results (updated):")
for model_name, metrics in priority_results.items():
    print(f"\n--- {model_name} ---")
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print("Classification Report:")
    print(metrics['report'])

All Priority Model Results (updated):

--- Logistic Regression (Balanced) ---
Accuracy: 0.8865
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.81      0.90       318
           1       0.95      0.84      0.89       426
           2       0.80      0.97      0.88       533

    accuracy                           0.89      1277
   macro avg       0.92      0.87      0.89      1277
weighted avg       0.90      0.89      0.89      1277


--- Logistic Regression (Standard) ---
Accuracy: 0.8872
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.81      0.90       318
           1       0.96      0.83      0.89       426
           2       0.80      0.98      0.88       533

    accuracy                           0.89      1277
   macro avg       0.92      0.87      0.89      1277
weighted avg       0.90      0.89      0.89      1277


--- Multinomial Naive Bayes ---
Accuracy: 0.8825
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.81      0.90       318
           1       0.98      0.80      0.88       426
           2       0.79      0.99      0.88       533

    accuracy                           0.88      1277
   macro avg       0.92      0.87      0.88      1277
weighted avg       0.90      0.88      0.88      1277


--- Decision Tree (Balanced) ---
Accuracy: 0.8583
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.86      0.85       318
           1       0.87      0.87      0.87       426
           2       0.86      0.85      0.86       533

    accuracy                           0.86      1277
   macro avg       0.86      0.86      0.86      1277
weighted avg       0.86      0.86      0.86      1277


--- Random Forest (Balanced) ---
Accuracy: 0.8583
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.84      0.86       318
           1       0.86      0.86      0.86       426
           2       0.85      0.86      0.86       533

    accuracy                           0.86      1277
   macro avg       0.86      0.86      0.86      1277
weighted avg       0.86      0.86      0.86      1277


--- XGBoost ---
Accuracy: 0.8684
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.82      0.87       318
           1       0.89      0.85      0.87       426
           2       0.83      0.91      0.87       533

    accuracy                           0.87      1277
   macro avg       0.88      0.86      0.87      1277
weighted avg       0.87      0.87      0.87      1277

In [ ]:
import ipywidgets as widgets
from IPython.display import display

email_input = widgets.Textarea(
    value='',
    placeholder='Type or paste the email here...',
    description='Email Input:',
    layout={'width': '800px', 'height': '200px'}
)

display(email_input)

Textarea(value='', description='Email Input:', layout=Layout(height='200px', width='800px'), placeholder='Type…

In [ ]:
def preprocess_email(email_content):
    # 1. Retrieve the content of the user-provided email (already passed as email_content)

    # 2. Apply the remove_urls function
    processed_email = remove_urls(email_content)

    # 3. Apply the remove_special_characters_and_normalize_spaces function
    processed_email = remove_special_characters_and_normalize_spaces(processed_email)

    # 4. Convert the processed email to lowercase
    processed_email = processed_email.lower()

    # 5. Apply the remove_stopwords function
    processed_email = remove_stopwords(processed_email)

    # 6. Apply the apply_lemmatization function
    preprocessed_email = apply_lemmatization(processed_email)

    return preprocessed_email

# Example usage with a dummy email for demonstration
email_input.value = """Hello Team, please check this important link: http://example.com/urgent and provide your feedback by 5pm! Thanks! #work
"""

example_email_content = email_input.value
preprocessed_example = preprocess_email(example_email_content)

print(f"Original Email:\n{example_email_content}")
print(f"Preprocessed Email:\n{preprocessed_example}")

Original Email:
Hello Team, please check this important link: http://example.com/urgent and provide your feedback by 5pm! Thanks! #work

Preprocessed Email:
hello team please check important link provide feedback 5pm thanks work

In [ ]:
def vectorize_email(preprocessed_email_text):
    # Ensure the input is in a list format as expected by transform
    return tfidf_vectorizer.transform([preprocessed_email_text])

# Example usage with the preprocessed example email
vectorized_example = vectorize_email(preprocessed_example)

print(f"Vectorized Example Shape: {vectorized_example.shape}")

Vectorized Example Shape: (1, 5000)

In [ ]:
def classify_spam_ham(vectorized_email):
    # Use the pre-trained logistic_regression_balanced_model to predict
    prediction = logistic_regression_balanced_model.predict(vectorized_email)
    # The model predicts 0 for ham, 1 for spam
    return 'Spam' if prediction[0] == 1 else 'Ham'

# Example usage with the vectorized example email
spam_ham_prediction = classify_spam_ham(vectorized_example)

print(f"Spam/Ham Prediction for example email: {spam_ham_prediction}")

Spam/Ham Prediction for example email: Spam

In [ ]:
def integrate_classification_pipeline(email_content):
    # 1. Preprocess the email content
    preprocessed_email = preprocess_email(email_content)

    # 2. Vectorize the preprocessed email
    vectorized_email = vectorize_email(preprocessed_email)

    # 3. Classify the email as spam or ham
    spam_ham_status = classify_spam_ham(vectorized_email)

    # 4. Implement conditional check for ham/spam and priority classification
    if spam_ham_status == 'Ham':
        # Predict priority if it's ham
        priority_prediction = logistic_regression_priority_model.predict(vectorized_email)

        # Map numerical priority to string labels
        priority_mapping_reverse = {0: 'Low', 1: 'Medium', 2: 'High'}
        predicted_priority_label = priority_mapping_reverse[priority_prediction[0]]

        return f"Ham (Priority: {predicted_priority_label})"
    else:
        return "Spam Email"

print("Master classification pipeline function 'integrate_classification_pipeline' defined.")

Master classification pipeline function 'integrate_classification_pipeline' defined.

In [ ]:
import ipywidgets as widgets
from IPython.display import display

# Assuming email_input is already defined from a previous step
# The redundant creation of email_input is removed from here.

# 1. Create a button
classify_button = widgets.Button(description='Classify Email')

# 2. Create an output widget to display results
output_widget = widgets.Output()

# 3. Define the function to be executed when the button is clicked
def on_classify_button_clicked(b):
    with output_widget:
        output_widget.clear_output() # a. Clear the output widget
        email_content = email_input.value # b. Get the current email content
        if not email_content.strip():
            print("Please enter an email to classify.")
            return

        # c. Call the integrate_classification_pipeline function
        result = integrate_classification_pipeline(email_content)

        # d. Display the classification result
        print(f"Classification Result: {result}")

# 4. Attach the function as an event handler to the button's on_click method
classify_button.on_click(on_classify_button_clicked)

# 5. Display the input widget, button, and output widget
display(email_input, classify_button, output_widget)
print("Interactive classification tool initialized. Enter email above and click 'Classify Email'.")

Textarea(value='Hello Team, please check this important link: http://example.com/urgent and provide your feedb…

Button(description='Classify Email', style=ButtonStyle())

Output()

Interactive classification tool initialized. Enter email above and click 'Classify Email'.